name: facebook_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  intl: 0.19.0
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/Facebook-Avatar.jpg
    - assets/images/Hello World.png
    - assets/images/Bearface.png
    - assets/images/John Xina.png
    - assets/images/Romil Hemnani.png
    - assets/images/Saturation.png
    - assets/images/Suguru Geto.png
    - assets/images/Unthinkable.png
    - assets/images/JJK Trio.png
    - assets/images/Pol Pot.png
    - assets/images/Tiananmen Square.png
    - assets/images/Sigma Cat.png
    - assets/images/Chill Guy.png
    - assets/images/AFK Journey.png
    - assets/images/The Family.png
    - assets/images/Red Guitar.png
    - assets/images/Vhonster Logo.png
    - assets/images/Jollibee.png
    - assets/images/Jollideals.png
    - assets/images/PSBank.png
    - assets/images/PSBankAd.jpg
    - assets/images/Smart.png
    - assets/images/SmartAd.png
    - assets/images/Rolex.png
    - assets/images/RolexAd.png
    - assets/images/Nike.png
    - assets/images/NikeAd.png
  fonts:
    - family: Klavika
      fonts:
        - asset: assets\fonts\KlavikaBoldBold.otf
    - family: Frutiger
      fonts:
        - asset: assets\fonts\FrutigerLTStd-Roman.otf
  uses-material-design: true
